# Minimal Meta Server Main Configuration
# This configuration contains the main server settings (logging, server config, etc.)
# Note: This should be used with minimal_meta_launcher_config.toml and minimal_meta_app_config.toml

# Basic logging configuration
[[common.log.categories]]
categories = [ '.' ]
handlers = [ 'console' ]
inherit = true
level = 'INFO'
propagate = 'NONE'

[[common.log.handlers]]
async = false
name = 'console'
stream_type = 'STDERR'
writer_type = 'STREAM'

# Monitor configuration (minimal)
[common.monitor]
flush_interval = '10s'

[[common.monitor.reporters]]
type = 'monitor_collector'

[common.monitor.reporters.monitor_collector]
remote_ip = '127.0.0.1:9001'

# Server configuration
[server]
use_memkv = true  # Use in-memory KV instead of FDB

# Network configuration - TCP only
[server.base]
groups_length = 1

[[server.base.groups]]
network_type = 'TCP'
services = [ 'MetaSerde' ]
use_independent_thread_pool = false

[server.base.groups.listener]
listen_port = 8000
listen_queue_depth = 1024
reuse_port = false

[server.base.groups.processor]
enable_coroutines_pool = true
max_coroutines_num = 64
max_processing_requests_num = 1024

[server.base.groups.io_worker]
num_event_loop = 1
tcp_connect_timeout = '5s'
read_write_tcp_in_event_thread = false

# KV Engine configuration - In-Memory
[server.kv_engine]
use_memkv = true

# Meta service configuration (minimal)
[server.meta]
authenticate = false
batch_stat_concurrent = 4
check_file_hole = false
dynamic_stripe = false
enable_fileinfo_cache = false
enable_hardlink = false
enable_inode_cache = false
enable_path_cache = false
enable_trash = false
inode_cache_size = 1000
max_file_size = 1099511627776  # 1TB
max_path_size = 4096
readonly = false
stripe_size = 1048576  # 1MB
test_mode = false

# Background client configuration (minimal)
[server.background_client]
default_timeout = '5s'
force_use_tcp = true

[server.background_client.io_worker]
num_event_loop = 1
tcp_connect_timeout = '5s'
read_write_tcp_in_event_thread = false

# Mgmtd client configuration (minimal)
[server.mgmtd_client]
mgmtd_server_addresses = [ 'TCP://127.0.0.1:7000' ]
conn_timeout = '5s'
call_timeout = '10s'

# Storage client configuration (minimal)
[server.storage_client]
default_timeout = '5s'
force_use_tcp = true

[server.storage_client.io_worker]
num_event_loop = 1
tcp_connect_timeout = '5s'
read_write_tcp_in_event_thread = false

[server.storage_client.retry]
init_wait_time = '1s'
max_wait_time = '5s'
max_retry_time = '5s'
max_failures_before_failover = 3
